name: gunwave
description: A pixel adventure and shooting game with hand gesture recognition.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: 3.4.1
  flutter_dotenv: 5.2.1
  flutter_riverpod: 2.6.1
  flutter_svg: 2.1.0
  go_router: 15.0.0
  google_fonts: 6.2.1
  gradient_borders: 1.0.1
  intl: 0.20.2
  permission_handler: 12.0.0+1
  random_avatar: 0.0.8
  string_validator: 1.1.0
  flame: 1.26.1
  flame_tiled: 2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/hub/joystick/
    - assets/tiles/
    - assets/images/
    - assets/images/ui/buttons/
    - assets/images/ui/banners/
    - assets/images/buildings/tower/
    - assets/images/effects/fire/
    - assets/images/terrain/
    - assets/images/resources/trees/
    - assets/images/terrain/water/
    - assets/images/terrain/water/foam/
    - assets/images/terrain/water/rocks/
    - assets/images/factions/knights/warrior/blue/
    - assets/images/factions/monsters/torch/blue/